### PR TITLE
Add Ruby 3.2 and Windows CI tests

### PR DESCRIPTION
**Pull request by tung-vu-td**
- Adding CI tests for Ruby 3.2
- Adding CI tests for Windows
- Remove Gemfile.lock due to different gems of Linux and Windows

### CODE REVIEW

**Review by kietdo360 — APPROVED** [review]
LGTM

**Comment by daipom** [comment]
Thanks for adding Ruby 3.2 and Windows tests!

Do we also use GitHub actions for Windows test? (a6fe57593af0998233c6fee810275aa9c58043cb)

**Comment by tung-vu-td** [comment]
@daipom Yes, I added the windows tests for Github actions as well on top of CircleCI window test to cover different versions of Ruby. Looks like it simplifies a lot compare to CircleCI for testing on windows. I still need to keep CircleCI tests for linux and deployment as well, at least for now

**Review by nmpennypacker — APPROVED** [review]
Reviewed for data exfiltrations

**Comment by daipom** [comment]
> @daipom Yes, I added the windows tests for Github actions (based on your PR) as well on top of CircleCI window test to cover different versions of Ruby. Looks like it simplifies a lot compare to CircleCI for testing on windows. I still need to keep CircleCI tests for linux and deployment as well, at least for now

I see! Thanks for the explanation!

**Comment by tung-vu-td** [comment]
@daipom Huge thanks for helping us with these tests.

Regarding support for 3.2. Since we don't add any new code, I assume you can use the latest version (1.2.1) without any issue? Or am I missing something and still need to release new version?

**Comment by daipom** [comment]
Thanks so much!
I was checking each embedded plugin of td-agent since the next package will embed Ruby 3.2.
I think it is ok since the test is successful with Ruby 3.2!

Thanks for adding tests!

**Pull request merged**
