### PR TITLE
update td-client dependency to fit for td-agent3

### PR DESCRIPTION
**Pull request by tagomoris**
`td-client-ruby` version 1.0 has been released.

### CODE REVIEW

**Comment by tagomoris** [comment]
@repeatedly could you check & release?

**Comment by repeatedly** [comment]
This is handled by https://github.com/treasure-data/fluent-plugin-td/pull/25 .
I will release new version soon.

**Comment by tagomoris** [comment]
I missed it... .but are you proceeding such release without any reviews every time?

**Comment by repeatedly** [comment]
@tagomoris td plugin release is customer basis. So I discussed / reviewed features by support and customer testing.

**Pull request closed without merging**
